In [2]:
import glob
import numpy as np
import cv2 as cv
from matplotlib import pyplot as plt

In [6]:
def read_images(filename):
    imgfiles = (glob.glob(filename))
    images = []
    for imgfile in imgfiles:
        image = (cv.imread(imgfile,0)) 
        images.append(cv.resize(image, (250,250), interpolation = cv.INTER_AREA)) 
        
    return images

In [7]:
def linear_dimention(convlist):
    for i in range(0,len(convlist)):
        convlist[i] = convlist[i].ravel()

In [8]:
banana_images = read_images("/Users/j/Desktop/programming/ML/github/image_recognition/data/banana/*.jpg")
not_banana_images = read_images("/Users/j/Desktop/programming/ML/github/image_recognition/data/notbanana/*.jpg")

In [104]:
linear_dimention(banana_images)
linear_dimention(not_banana_images)

In [105]:
np.shape(banana_images)

(46, 62500)

In [106]:
np.shape(not_banana_images)

(129, 62500)

In [107]:
x_traindata = np.array(banana_images+not_banana_images)

In [108]:
np.shape(x_traindata)

(175, 62500)

In [109]:
y_traindata = np.zeros(175)

In [110]:
np.shape(y_traindata)

(175,)

In [111]:
y_traindata[0:45] = 1
# 1 - isbanana 0 - not banana

In [112]:
x_traindata[0]

array([204, 202, 197, ..., 160, 160, 159], dtype=uint8)

In [113]:
from sklearn.neural_network import MLPClassifier

In [114]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)
clf.fit(x_traindata, y_traindata) 

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=1, shuffle=True, solver='lbfgs', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [140]:
test = read_images("/Users/j/Desktop/programming/ML/github/image_recognition/data/banana/test/*.jpg")

In [141]:
linear_dimention(test)

In [142]:
test

[array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([253, 253, 253, ..., 253, 253, 253], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([252, 252, 252, ..., 252, 252, 252], dtype=uint8)]

In [143]:
clf.predict(np.array(test))

array([1., 1., 1., 1., 1.])